baseURL = '/'
languageCode = 'en-us'
title = 'other faces'
theme = 'holy'



[markup.goldmark.renderer]
  unsafe = true

[params]
  copyright = "otherfacesband@gmail.com"

  [params.author]
  name = "Kristian"

[menu]
  [[menu.main]]
    identifier = "home"
    url = "/home/"
    weight = 10
  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about/"
    weight = 11